name:                abstract-files
version:             0.1.0.0
github:              "yarkivaev/abstract-files"
license:             MIT
author:              "Yaroslav"
maintainer:          "yarkivaev@gmail.com"
copyright:           "2025 Yaroslav"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yarkivaev/abstract-files#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- filepath
- directory
- aeson
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  abstract-files-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - abstract-files
    - hspec
    - temporary
